version: '3'
services:
  web:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  app:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306


# env.example をコピーして、.env を作成する
# docker-compose build
# docker-compose up -d
# docker-compose exec app composer install
# docker-compose exec app php artisan migrate
# http://localhost にアクセスして、Laravelのトップページが出てきたら環境構築完了


# 初回起動時(ビルド)
# docker-compose build --no-cache
# docker-compose up -d
# .env.example をコピーして、.env を作成し、内容を書き換える
# docker-compose exec web rails db:create

# 起動
# docker-compose up -d

# 再起動
# docker-compose restart

# 停止
# docker-compose stop

# 削除するときはこれ
# docker-compose down --rmi all --volumes

